github: Add code coverage to backend test workflow
Signed-off-by: yolossn <sannagaraj@microsoft.com>

diff --git a/.github/workflows/backend-test.yml b/.github/workflows/backend-test.yml
--- a/.github/workflows/backend-test.yml
+++ b/.github/workflows/backend-test.yml
@@ -1,30 +1,104 @@
 name: Backend test
+
 on:
   pull_request:
     paths:
-    - 'backend/**'
+      - 'backend/**'
 
+env:
+  HEADLAMP_RUN_INTEGRATION_TESTS: true
 
 jobs:
   build:
     runs-on: ubuntu-latest
-    name: Test backend
+
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-    - name: Setup go
-      uses: actions/setup-go@v4
-      with:
-        go-version: '1.20.*'
-    - name: Setup minikube cluster
-      uses: medyagh/setup-minikube@master
-    - name: Start cluster
-      run: |
-        minikube start --driver=docker
-    - name: Check cluster status 
-      run: |
-        minikube status
-    - name: Run golang test
-      run: |
-        export HEADLAMP_RUN_INTEGRATION_TESTS=true
-        make backend-test
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+    
+      - uses: actions/setup-go@v3
+        with:
+          go-version: 1.20.5
+    
+      - name: Install dependencies
+        run: |
+          cd backend
+          go mod download
+    
+      - name: Start cluster
+        uses: medyagh/setup-minikube@master
+
+      - name: Check cluster status 
+        run: |
+          minikube status
+
+      - name: Enable headlamp addon
+        run: |
+          minikube addons enable headlamp
+
+      - name: Try the cluster!
+        run: kubectl get pods -A
+        
+      - name: Run tests and calculate code coverage
+        run: |
+          cd backend
+          go test ./... -coverprofile=coverage.out -covermode=atomic -coverpkg=./...
+          testcoverage=$(go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
+          echo "Code coverage: $testcoverage"
+          echo "coverage=$testcoverage" >> $GITHUB_ENV
+        shell: bash
+
+      - name: Get base branch code coverage
+        run: |
+          cd backend
+          ls
+          base_branch="${{ github.base_ref }}"
+          testcoverage="${{ env.coverage }}"
+          if [ "$base_branch" = "main" ]; then
+            echo "Base branch is main, using current test coverage value: $base_coverage"
+            base_coverage="$testcoverage"
+          else
+            git fetch origin "$base_branch"
+            git checkout "origin/$base_branch"
+            go test ./... -coverprofile=base_coverage.out -covermode=atomic -coverpkg=./...
+            base_coverage=$(go tool cover -func=base_coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
+          fi
+          echo "Base branch code coverage: $base_coverage"
+          echo "base_coverage=$base_coverage" >> $GITHUB_ENV
+        shell: bash
+
+      - name: Compare code coverage
+        run: |
+          testcoverage="${{ env.coverage }}"
+          base_coverage="${{ env.base_coverage }}"
+          if [[ -z $testcoverage || -z $base_coverage ]]; then
+            echo "testcoverage or base_coverage is not set. Cannot calculate coverage difference."
+            exit 1
+          fi
+          
+          echo "testcoverage=$testcoverage"
+          echo "base_coverage=$base_coverage"
+          echo "$testcoverage - $base_coverage"
+
+          coverage_diff=$(echo "$testcoverage - $base_coverage" | bc)
+          echo "Coverage change: $coverage_diff"
+          echo "coverage_diff=$coverage_diff" >> $GITHUB_ENV
+        shell: bash
+
+      - name: Comment on PR
+        run: |
+          testcoverage="${{ env.coverage }}"
+          base_coverage="${{ env.base_coverage }}"
+          coverage_diff="${{ env.coverage_diff }}"
+          if (( $(echo "$coverage_diff < 0" | bc -l) )); then
+            emoji="😞" # Decreased coverage
+          else
+            emoji="😃" # Increased or unchanged coverage
+          fi
+
+          comment="Code coverage $emoji changed from $base_coverage% to $testcoverage%. Change: $coverage_diff%."
+          echo "$comment"
+          gh issue comment ${{github.event.number}} --body "${comment}"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
